name: API Auto Test CI/CD

# 触发条件：当有代码 push 到 main 分支时，自动触发流水线
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # 免费白嫖 GitHub 提供的最新版 Ubuntu 云服务器

    steps:
      - name: 1. 拉取最新代码
        uses: actions/checkout@v3

      - name: 2. 配置 Java 8 环境
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven # 开启 Maven 缓存，以后跑得更快

      - name: 3. 执行 Maven 接口自动化测试
        run: mvn clean test
        continue-on-error: true # 极其重要：即使测试有用例失败（爆红），也要继续往下走去生成报告！

      - name: 4. 生成 Allure 测试报告
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: 5. 自动部署报告到 GitHub Pages (生成公开网页)
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # 把网页代码推送到一个叫 gh-pages 的新分支
          publish_dir: allure-history